apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scas-production-ingress
  namespace: scas-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: scas.rvce.edu.in
      http:
        paths:
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: scas-backend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: scas-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scas-frontend
                port:
                  number: 80
