spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health

---

spring:
  config:
    activate:
      on-profile: prod
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health