name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check folder structure
        run: |
          test -d backend || (echo "Missing backend folder" && exit 1)
          test -d frontend || (echo "Missing frontend folder" && exit 1)
          test -d ml-service || (echo "Missing ml-service folder" && exit 1)
          test -d infra || (echo "Missing infra folder" && exit 1)
          test -d docs || (echo "Missing docs folder" && exit 1)

      - name: Check required files
        run: |
          test -f .gitignore || (echo ".gitignore missing" && exit 1)
          test -f .editorconfig || (echo ".editorconfig missing" && exit 1)

      - name: Dummy build step
        run: echo "Basic validation passed"